title: Sukwoo Hong
logo: /assets/img/ryan2.JPG
description: **Growth Marketing @LINE**  
description: **Business Development @Poolus**  
description: **Performance Marketing @WeWork**
show_downloads: False
theme: jekyll-theme-minimal
